// Auth
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_REQUEST_SENDING = 'AUTH_REQUEST_SENDING';
export const AUTH_REQUEST_SENDED = 'AUTH_REQUEST_SENDED';
export const AUTH_TOKEN_READY = "AUTH_TOKEN_READY"

// Auth forms 

export const AUTH_PARAM_SET = 'AUTH_PARAM_SET';



// Cats CRUD

export const GET_CATS_SUCCESS = "GET_CATS_SUCCESS";
export const GET_CAT_SUCCESS = "GET_CAT_SUCCESS";
export const DELETE_CAT_SUCCESS = "DELETE_CAT_SUCCESS";
export const UPDATE_CAT_SUCCESS = "UPDATE_CAT_SUCCESS";
export const CREATE_CAT_SUCCESS = "CREATE_CAT_SUCCESS";
export const CAT_REQUEST_SENDING = "CAT_REQUEST_SENDING";
export const CAT_REQUEST_SENDED = "CAT_REQUEST_SENDED";

// Cat forms

export const UPDATE_CAT_PARAM_SET = 'UPDATE_CAT_PARAM_SET';
export const CREATE_CAT_PARAM_SET = 'CREATE_CAT_PARAM_SET';

